[project]
name = "scripts"
version = "0.1.0"
description = "Utility scripts used to modify a Ren'Py game"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "casefy>=1.1.0",
    "pillow>=12.0.0",
]
