name: build-and-deploy
on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Verify tag is on main
        run: |
          if ! git branch --contains ${{ github.ref }} | grep -q '^  main$'; then
            echo "Tag is not on main; skipping release."
            exit 1
          fi

      - name: Setup Ren'Py
        uses: remarkablegames/setup-renpy@v2
        with:
          web: true

      - name: Delete unnecessary files
        run: >
          find .
          ! -name "icon.*"
          ! -name "progressive_download.txt"
          ! -name "version.txt"
          ! -name "web-*"
          ! -path "*/.*"
          ! -path "*game*"
          -delete

      - name: Build packages
        run: renpy-launcher distribute . --dest ../dists

      - name: Rename packages
        run: |
          # e.g., "../dists/untitled-novembuck-game-1.2.3-linux.tar.bz2" -> "../dists/linux.tar.bz2"
          for filename in ../dists/*; do mv "$filename" "../dists/${filename##*-}"; done

      - name: Build web
        run: |
          renpy-launcher web_build . --destination ../dists/web
          rm ../dists/web/web-presplash.jpg
          mv web-presplash.webp ../dists/web
          grep -lr web-presplash.jpg ../dists/web | xargs sed -i 's/web-presplash.jpg/web-presplash.webp/g'

      - name: Setup butler
        uses: remarkablegames/setup-butler@v2

      # https://www.renpy.org/doc/html/build.html#var-build.itch_channels
      - name: Upload to itch.io
        run: |
          for i in "web web" "linux.tar.bz2 linux" "mac.zip osx" "win.zip win"
          do
            set -- $i
            butler push ../dists/$1 ${{ github.repository }}:$2 --userversion-file version.txt
          done
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

      - name: Create GitHub Release
        uses: "softprops/action-gh-release@v2"
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Artifact
        run: gh release upload ${{ github.ref_name }} $(ls ../dists/*.zip)
        env:
          GH_TOKEN: ${{ github.token }}
